### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by fscii** [sbcshop/Spi-Box#1]
Can't open pdf once downloaded.
"Couldn't open this pdf.  Something's keeping this pdf from opening."
Same message on Windows 10 and RPI 3+ Raspian Stretch

**Comment by fscii** [comment]
Actually its the entire software setup that is corrupt and can't be downloaded/used.  Its been 23 days no response.  Hello?

**Comment by sbcshop** [comment]
Hi Fscii,

Sorry for the inconvenience.

The Spi-Box software is upgraded and PDF is also updated.

Regards
SB Team
